version: '2.0'

services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./team/
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - ./team/:/usr/src/app/
    ports:
      - 8008:8008
      - 8888:8888
    environment:
      - SQL_ENGINE=django.db.backends.mysql
      - SQL_DATABASE=team_mgmt
      - SQL_USER=team_user
      - SQL_PASSWORD=team123@#_
      - SQL_HOST=db
      - SQL_PORT=3306
      - DATABASE=mysql
    depends_on:
      - db
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=team_user
      - MYSQL_PASSWORD=team123@#_
      - MYSQL_ROOT_PASSWORD=r00t123@#_
      - MYSQL_DATABASE=team_mgmt
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx


  ui:
    build:
      dockerfile: Dockerfile.dev
      context: ./team_ui
    volumes:
      - /app/node_modules
      - ./team_ui:/app
    ports:
      - 3000:3000

volumes:
  mysql_data: