# Generated by Django 3.0.4 on 2020-03-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
