export const teamConstants = {
    TEAM_TABLE_START: 'FETCH_EOX_TABLE_DATA_BEGIN',

    TEAM_TABLE_GET_SUCCESS: 'FETCH_TEAM_TABLE_GET_SUCCESS',
    TEAM_TABLE_POST_SUCCESS: 'FETCH_TEAM_TABLE_POST_SUCCESS',
    TEAM_TABLE_PUT_SUCCESS: 'FETCH_TEAM_TABLE_PUT_SUCCESS',
    TEAM_TABLE_DELETE_SUCCESS: 'FETCH_TEAM_TABLE_DELETE_SUCCESS',

    TEAM_TABLE_FAIL: 'FETCH_EOX_TABLE_DATA_FAIL'

}